import type { VerticalConfig } from './types'

const v = (
  id: string,
  title: string,
  titleFa: string,
  family: VerticalConfig['family'],
  headline: string,
  subheadline: string,
  primaryCta: string,
  secondaryCta: string,
  accent: string,
  accent2: string,
  widgets: string[],
  sections: string[],
  flows: string[],
  proof: string[],
): VerticalConfig => ({
  id, title, titleFa, family, headline, subheadline, primaryCta, secondaryCta,
  accent, accent2, widgets, sections, flows, proof,
  eyebrow: `${title} · vertical experience kit`,
})

export const verticals: VerticalConfig[] = [
  v('real-estate','Real Estate','مشاور املاک','real-estate','Find the right property before everyone else does.','A high-intent property experience built around matching, not endless browsing.','Find my property','Browse listings','#d6ff45','#5eead4',['Property finder','My ideal property form','Budget + area filters','Compare listings'],['Featured listings','Neighborhood explorer','Buyer / renter paths','Agent proof'],['Match request','Viewing booking','Callback'],['Fresh inventory','Verified files','Fast matching']),
  v('beauty-salon','Beauty Salon','سالن زیبایی زنانه','booking','Your next appointment, beautifully simple.','Turn empty calendar slots into booked treatments with a tactile booking flow.','Book a treatment','See services','#ff6aa8','#ffd6e7',['Service selector','Live time slots','Specialist picker','Bridal package request'],['Popular services','Portfolio','Seasonal offers','Bridal experience'],['Service → specialist → time','Package inquiry','Waitlist'],['Live availability','Expert team','Premium care']),
  v('barbershop','Barbershop','آرایشگاه مردانه','booking','Choose the cut. Choose the barber. Own the look.','A sharper booking experience with style-first discovery and barber selection.','Book your barber','Explore styles','#c8ff3d','#ff7a00',['Barber selector','Style gallery','Time slots','VIP booking'],['Signature cuts','Barber profiles','Memberships','Lookbook'],['Style → barber → slot','VIP request','Membership'],['Skilled barbers','On-time slots','Fresh work']),
  v('auto-gallery','Auto Gallery','اتوگالری','catalog','The right car should feel obvious.','A cinematic vehicle catalog with trade-in and purchase intent built into every listing.','Explore inventory','Value my car','#9be7ff','#6d5dfc',['Vehicle catalog','Brand/model filters','Trade-in form','Sell your car'],['Featured cars','Finance paths','Compare cars','Why buy from us'],['Browse → compare → inquire','Trade-in','Sell request'],['Verified inventory','Trade-in ready','Fast response']),
  v('aesthetic-clinic','Aesthetic Clinic','کلینیک زیبایی','consultation','Confidence starts with the right consultation.','Service education, before/after storytelling and a low-friction consultation flow.','Book consultation','See results','#ffd3c8','#b79cff',['Consultation booking','Before/after slider','Treatment selector','Quick assessment'],['Treatments','Experts','Results','Treatment journey'],['Concern assessment','Consultation','Follow-up'],['Expert-led','Private consultation','Natural results']),
  v('dentistry','Dentistry','دندانپزشکی','consultation','A clearer path to a healthier smile.','Turn uncertainty into an informed next step with service estimation and appointment booking.','Book appointment','Check my options','#8fe8ff','#c8ffea',['Appointment booking','Initial estimator','Reminder opt-in','Symptom triage'],['Treatments','Team','Insurance','Smile stories'],['Need → estimate → visit','Urgent request','Reminder'],['Clear estimates','Modern care','Flexible visits']),
  v('gym','Fitness Club','باشگاه ورزشی','booking','Find the class that makes you come back.','Classes, memberships and trial sessions wrapped in a high-energy conversion flow.','Start free trial','See classes','#d8ff45','#ff5f57',['Class schedule','Trial booking','Membership selector','Goal quiz'],['Classes','Coaches','Weekly schedule','Member results'],['Goal → trial → membership','Class booking','Coach intro'],['Flexible plans','Real coaches','Strong community']),
  v('personal-trainer','Personal Trainer','مربی شخصی','booking','Training built around you, not a template.','Personal profile, session booking and program packages in one premium coaching experience.','Book a session','View programs','#ff8a5c','#ffd84d',['Coach profile','Session booking','Package picker','Goal assessment'],['Method','Transformations','Programs','Client stories'],['Goal → package → session','Consultation','Program signup'],['1:1 coaching','Measurable progress','Flexible sessions']),
  v('language-school','Language School','آموزشگاه زبان','education','Start at the level that actually fits you.','A guided placement experience that recommends the right class instead of making users guess.','Take placement test','Talk to advisor','#7c6cff','#6ee7ff',['Placement test','Language picker','Class matcher','Consultation booking'],['Courses','Teachers','Method','Levels'],['Assess → recommend → enroll','Advisor booking','Trial class'],['Smart placement','Expert teachers','Clear progression']),
  v('exam-academy','Exam Academy','آموزشگاه کنکور','education','Turn study pressure into a plan.','Student assessment, personalized plan suggestions and advisor booking for exam preparation.','Assess my plan','See programs','#ffcf48','#ff6b6b',['Student assessment','Study-plan matcher','Major/grade selector','Advisor booking'],['Top results','Programs','Advisors','Study system'],['Assess → plan → advisor','Program signup','Progress check'],['Personal plan','Progress tracking','Experienced advisors']),
  v('auto-repair','Auto Repair','تعمیرگاه خودرو','estimator','Know what your car needs before the visit.','Service booking, issue diagnosis and rough pricing in a trust-first automotive flow.','Diagnose issue','Book service','#ffb347','#ff5f57',['Service booking','Issue selector','Price estimator','Maintenance reminder'],['Services','Periodic maintenance','Workshop proof','Reviews'],['Issue → estimate → slot','Reminder','Callback'],['Transparent work','Fast booking','Service history']),
  v('auto-parts','Auto Parts','فروشگاه لوازم یدکی','catalog','The right part, for the exact car.','Model-aware part search with stock request and fast quote flows.','Find my part','Request a part','#71d7ff','#ffd84d',['Vehicle model search','Part request','Stock inquiry','Quick order'],['Best sellers','Brands','Authenticity','Delivery'],['Vehicle → part → request','Stock check','Quote'],['Model matched','Original brands','Fast dispatch']),
  v('detailing','Detailing Studio','کارواش / دیتیلینگ','booking','Make the car look new again.','Package-led booking with tactile upsells, before/after proof and premium positioning.','Choose a package','See transformations','#6ee7ff','#9b7cff',['Package picker','Booking calendar','Upsell selector','Membership'],['Packages','Before/after','VIP services','Membership'],['Package → extras → time','Membership','Pickup request'],['Premium products','Detail-focused','Easy booking']),
  v('fashion-atelier','Fashion Atelier','مزون / لباس مجلسی','catalog','Find the dress that already feels like yours.','An editorial catalog with fitting reservations, sizing and wishlisting.','Explore collection','Book a fitting','#ff9fc8','#f5d0fe',['Collection catalog','Fitting booking','Size intake','Wishlist'],['Collections','Bridal edit','New arrivals','Client looks'],['Look → fitting → size','Bridal inquiry','Wishlist'],['Curated pieces','Private fitting','New drops']),
  v('jewelry','Jewelry','طلافروشی','catalog','A digital showcase worthy of the piece.','Luxury browsing with live-price context, private visit booking and high-intent inquiry.','Explore collection','Book private visit','#f4c95d','#f8e7a1',['Digital showcase','Live-price strip','Visit booking','Budget filter'],['Collections','Featured pieces','Buying guide','Trust'],['Browse → shortlist → visit','Price inquiry','Private viewing'],['Curated gold','Price context','Private service']),
  v('furniture','Furniture & Interior','مبلمان / دکوراسیون','catalog','Start with a style. End with a room that feels yours.','Style-led discovery, project inquiry and quote capture for furniture and interiors.','Find my style','Request quote','#d3b79a','#849c7b',['Style selector','Collection browser','Project brief','Quote request'],['Styles','Projects','Materials','Consultation'],['Style → room → quote','Project inquiry','Consultation'],['Made to fit','Material options','Project support']),
  v('cabinet-maker','Cabinet Maker','کابینت‌ساز','estimator','See the project before you commit to it.','A guided estimator that collects dimensions, style and plan uploads before the sales call.','Estimate my kitchen','See projects','#f0b35a','#5e8c61',['Price estimator','Dimension intake','Style selector','Plan upload'],['Projects','Materials','Process','Warranty'],['Style → dimensions → estimate','Upload plan','Site visit'],['Rough estimate','Material choice','Measured workflow']),
  v('restaurant','Cafe & Restaurant','کافه / رستوران','hospitality','Come for the mood. Stay for what is on the table.','A sensory menu experience with reservations, daily offers and loyalty built in.','Reserve a table','See menu','#ff7a59','#ffd56b',['Smart menu','Table reservation','Offer of the day','Loyalty signup'],['Menu','Chef picks','Atmosphere','Location'],['Guests → date → table','Loyalty signup','Special request'],['Fresh menu','Easy booking','Member perks']),
  v('pet-care','Pet Care','پت‌شاپ / کلینیک دامپزشکی','pet','Everything your pet needs, remembered for you.','Pet profiles connect appointments, vaccine reminders and recurring purchases.','Create pet profile','Book a visit','#74dcae','#ffcf6e',['Pet profile','Vaccine reminder','Visit booking','Repeat purchase'],['Services','Vet team','Care plans','Recommended products'],['Pet → need → visit','Reminder setup','Repeat order'],['Pet history','Care reminders','Friendly team']),
  v('mobile-store','Mobile Store','فروشگاه موبایل','catalog','Upgrade without guessing what your old phone is worth.','Device catalog, trade-in calculator and purchase request in one fast retail experience.','Check trade-in','Browse phones','#7c9cff','#63e6be',['Trade-in calculator','Phone catalog','Model compare','Purchase request'],['Featured phones','Warranty','Trade-in steps','Accessories'],['Old phone → value → upgrade','Purchase request','Reserve device'],['Trade-in ready','Warranty','Current devices']),
  v('immigration','Immigration Services','خدمات مهاجرتی','consultation','Know your strongest route before you book the call.','Eligibility assessment turns a complex service into a clear, qualified consultation path.','Check eligibility','Book consultation','#5d8dff','#69d5c4',['Eligibility assessment','Country/path selector','Consultation booking','Lead score'],['Immigration routes','Process','Success stories','FAQ'],['Profile → eligibility → consult','Document readiness','Callback'],['Clear routes','Private review','Structured process']),
  v('travel-agency','Travel Agency','آژانس مسافرتی','hospitality','Tell us the trip. We will shape the options.','Destination, budget and date inputs turn into tailored tour recommendations.','Build my trip','Explore tours','#4ac7ff','#ffbe55',['Destination/budget form','Tour matcher','Date picker','Traveler count'],['Featured tours','Last minute','Destinations','Why book with us'],['Dream → budget → offers','Tour inquiry','Callback'],['Tailored trips','Flexible dates','Fast options']),
  v('insurance','Insurance','بیمه','consultation','Get a useful quote without the paperwork maze.','Fast quote capture, renewal reminders and policy guidance in a clear trust-first flow.','Get quick quote','Renew policy','#4f8cff','#76d7a7',['Quick quote','Policy selector','Renewal reminder','Coverage estimator'],['Insurance types','Benefits','Issuance steps','Trust'],['Need → quote → issue','Renewal','Advisor call'],['Fast quote','Renewal help','Clear coverage']),
  v('law-firm','Law Firm','دفتر حقوقی','consultation','Start with the right legal path.','Matter classification and consultation booking reduce uncertainty before the first conversation.','Identify my case','Book consultation','#c7a76a','#6f82a8',['Case-type diagnostic','Consultation booking','Case brief','Urgency selector'],['Practice areas','Lawyers','How we work','FAQ'],['Issue → matter → consult','Case brief','Callback'],['Confidential','Structured intake','Clear next step']),
  v('home-services','Home Services','خدمات ساختمان','estimator','Get the right technician moving, fast.','Urgent request, problem selection and rough estimate in a mobile-first service flow.','Request technician','Estimate cost','#ffb84d','#58b6ff',['Urgent request','Service selector','Rough estimate','Arrival window'],['Urgent services','How it works','Technicians','Transparent pricing'],['Problem → estimate → dispatch','Callback','Photo upload'],['Fast response','Skilled techs','Clear estimates']),
  v('hvac','HVAC Service','تأسیسات / کولر / پکیج','estimator','Diagnose first. Book the right service second.','Guided troubleshooting and service booking for HVAC, boiler and cooling systems.','Diagnose problem','Book service','#4dc6ff','#ff7b55',['Troubleshooter','Device selector','Service booking','Periodic reminder'],['Repair','Installation','Maintenance plans','FAQ'],['Device → symptom → service','Maintenance','Emergency'],['Guided diagnosis','Service slots','Maintenance reminders']),
  v('carpet-cleaning','Carpet Cleaning','قالیشویی','estimator','Know the pickup price in under a minute.','Simple carpet inputs become a transparent estimate and pickup order.','Calculate price','Book pickup','#6fc6b4','#f4c95d',['Price calculator','Carpet type selector','Pickup booking','Delivery window'],['Services','Pricing','Process','Benefits'],['Type → size → price','Pickup order','Status request'],['Upfront estimate','Pickup service','Tracked order']),
  v('dry-cleaning','Dry Cleaning','خشکشویی','estimator','Laundry pickup without the back-and-forth.','Item selection, pickup/delivery windows and recurring service in a fast ordering flow.','Schedule pickup','See services','#8dc6ff','#e5a8ff',['Pickup/delivery','Item selector','Delivery time','Subscription'],['Services','Pricing','Express','Membership'],['Items → pickup → delivery','Express order','Subscription'],['Doorstep service','Clear timing','Repeat orders']),
  v('photo-studio','Photography Studio','آتلیه عکاسی','booking','Choose the feeling before you choose the package.','Portfolio-led booking with package selection and a concise creative brief.','Book a shoot','View portfolio','#e8998d','#6d7cff',['Package selector','Portfolio','Booking calendar','Creative brief'],['Portfolio','Packages','Team','Process'],['Style → package → date','Project brief','Callback'],['Curated work','Clear packages','Planned sessions']),
  v('wedding-venue','Wedding Venue','تالار / باغ عروسی','hospitality','See what your date could feel like.','Availability, guest count and budget combine into a tailored venue package.','Check my date','Explore venue','#f3c8d8','#d8c36a',['Date availability','Guest count','Budget matcher','Visit booking'],['Spaces','Gallery','Packages','Add-ons'],['Date → guests → package','Venue tour','Custom quote'],['Live date check','Flexible packages','Private visit']),
]

export const verticalById = Object.fromEntries(verticals.map((item) => [item.id, item])) as Record<string, VerticalConfig>

export const familyLabels: Record<VerticalConfig['family'], string> = {
  'real-estate': 'Real estate', booking: 'Booking', catalog: 'Catalog + inquiry', consultation: 'Lead + consultation',
  estimator: 'Estimator + service', education: 'Education', hospitality: 'Food + travel + events', pet: 'Pet care',
}
